routes/web.php
<?php

//add use of any file that relevant to content up here
use App\Role;
use App\User;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*route for target page*/
Route::get('/', function () {
    return view('kkt');
});

//Here example of content function to aid for current function that dont have view
Route::get('/signup', function () {
	$roles = Role::all();
    return view('auth.signup',compact('roles'));
});

Route::get('/signup2', function () {
	$roles = Role::all();
    return view('kkt.kakitangan.signup',compact('roles'));
});

Route::get('/register2', function () {
    return view('auth.registerOri');
});

Route::get('/about', function () {
    return view('kkt2');
});

Route::get('/kktdashboard', function () {
    return view('kkt.kakitangan.dashboard');
});

Route::get('/leave/calendar', function () {
    return view('kkt.kakitangan.leave.calendar');
});

Route::get('/dashboard', function () {
    return view('layouts.kktinner');
});

Auth::routes();

Route::get('/home', 'HomeController@index');
Route::get('/getUser', 'UserController@getUser');
Route::get('/aggregate', 'UserController@aggregate');
Route::get('/join', 'UserController@join');
Route::get('/union', 'UserController@union');
Route::get('/getRole', 'ModelController@getRole');
Route::get('/insert', 'ModelController@insert');
Route::get('/update', 'ModelController@update');
Route::get('/updateOrCreate', 'ModelController@updateOrCreate');
Route::get('/pagination', 'PaginationController@pagination');
Route::get('/getInsert', 'CrudController@getInsert');
Route::post('/postInsert', 'CrudController@postInsert');
Route::get('/getUpdate/{id}', 'CrudController@getUpdate');
Route::post('/postUpdate/{id}', 'CrudController@postUpdate');
Route::get('/postDelete/{id}', 'CrudController@postDelete');
//post for pass data, get for create/destroy data
// Use {} to declare an id
Route::get('/getUser/{id}', 'UserController@getUser');

//----//
Route::get('manage-item-ajax', 'ItemAjaxController@manageItemAjax');
Route::resource('item-ajax', 'ItemAjaxController');

//--Crud Ajax--//
Route::get('/employees', 'CrudAjaxController@index');
Route::post('/create', 'CrudAjaxController@create');
Route::get('/edit/{user_id?}', 'CrudAjaxController@edit');
Route::put('/update/{user_id?}', 'CrudAjaxController@update');
Route::delete('/delete/{user_id?}', 'CrudAjaxController@delete');

Route::get('laravel-ajax-pagination',array('as'=>'ajax-pagination','uses'=>'FileController@productList'));

// Datatable CRUD AJAX
Route::get('datatable','DatatablesController@getIndex');
// uses of 'as=>' is important when want to use inside ajax 
Route::get('datatable/getIndexData','DatatablesController@getIndexData');
Route::post('/creating', 'DatatablesController@create');
Route::get('/editing/{user_id?}', 'DatatablesController@edit');
Route::put('/updating/{user_id?}', 'DatatablesController@update');
Route::delete('/remove/{user_id?}', 'DatatablesController@delete');

resources/views/contents.blade.php
@extends('layouts.app')
<!--where we use top headers same as home page-->

@section('content')

    <div class="content">
                <div class="title m-b-md">
                    Holiday Schedule
                </div>

                <p class="cblack"> Your current holiday left is : &nbsp <span id="totalday"></span></p>

                <input>

    </div>

@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/kkt2.blade.php
@extends('layouts.kkt')
<!--where we use top headers same as home page-->

@section('content')
<div class="content">
        <div class="gray_block">
          <div class="container title_line">
            <h2>ABOUT US</h2>
            <div class="subtitle">
              <p>You build great company. People is the most important asset in the company. Why are we treating people like 40 years ago?</p>
              <p>The most important HR work in the company -- (1) keep your great people engaged and motivated; (2) help everyone to perform better. Both of them takes a lot of time - have you done enough of them? Oh Leave, Payroll all these paperwork took all your time? Now, Let Kakitangan.com helps you. Let's make it smoother and we can dedicate your previous time in the real important HR work.</p>
              <p>You build great company. Kakitangan.com is honored to participate in your journey in building your great company.</p>
				    </div>
          </div>
        </div>
        <div class="container experts_wrap">
          <h3 class="text-center">OUR EXPERTS</h3>
          <ul class="person_list clearfix">
            <li class="person_item" style="background-image: url(/static/lp/img/person01.jpg);">
              <div class="person_title">RYAN WONG</div>
              <div class="person_position">
                Benefits Experts
              </div>
              <div class="person_experience">
                10 years experience
              </div>
              <i class="icon icon_arrow_up"></i>
              <div class="hovered_text">
                "I put together the best benefit plans for your employees."
              </div>
            </li>
            <li class="person_item" style="background-image:  url(/static/lp/img/person02.jpg);">
              <div class="person_title">NIZAM SHARI</div>
              <div class="person_position">
                HR Experts
              </div>
              <div class="person_experience">
                20 years experience
              </div>
              <i class="icon icon_arrow_up"></i>
              <div class="hovered_text">
                "The people make the company;<br> I make Kakitangan.com's people operations the best of its class, so the best people stay with you."
              </div>
            </li>
            <li class="person_item" style="background-image: url(/static/lp/img/person03.jpg);">
              <div class="person_title">MYROSLAV GALAVAI</div>
              <div class="person_position">
                UX Designer
              </div>
              <div class="person_experience">
                8 years experience
              </div>
              <i class="icon icon_arrow_up"></i>
              <div class="hovered_text">
                "I'm all about the craftmanship that makes every interaction on Kakitangan.com simple, graceful and productive."
              </div>
            </li>
          </ul>
        </div>

        <div class="container awards_wrap">
          <h3 class="text-center">
            OUR AWARDS
          </h3>
          <div class="carousel_wrap">
            <div id="owl-example2" class="owl-carousel carousel_styled simple_carousel">
              <div class="simple_carousel_item_content">
                <div class="simple_carousel_item_img">
                  <img src="/static/lp/img/alliance-bank-innovation.png" alt="alliance-bank">
                </div>
                <div class="simple_carousel_item_text">
                  Finalist – Alliance Bank SME Innovation Challenge 2015, Visa Award 2015
                </div>
              </div>
              <div class="simple_carousel_item_content">
                <div class="simple_carousel_item_img">
                  <img src="/static/lp/img/maybank.png" alt="maybank">
                </div>
                <div class="simple_carousel_item_text">
                  Finalist – Maybank Fintech 2016
                </div>
              </div>
              <div class="simple_carousel_item_content">
                <div class="simple_carousel_item_img">
                  <img src="/static/lp/img/cradle.png" alt="Cradle">
                </div>
                <div class="simple_carousel_item_text">
                  Cradle Investment Programme 150
                </div>
              </div>
              <div class="simple_carousel_item_content">
                <div class="simple_carousel_item_img">
                  <img src="/static/lp/img/magic.png" alt="">
                </div>
                <div class="simple_carousel_item_text">
                  MAGIC Cohort 2 ASEAN Accelerator Track
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>

@endsection

resources/views/manage-item-ajax.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Laravel Ajax CRUD Example</title>
	<meta name="csrf-token" content="{{ csrf_token() }}">
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/css/bootstrap.css">
</head>
<body>

	<div class="container">

		<div class="row">
		    <div class="col-lg-12 margin-tb">					
		        <div class="pull-left">
		            <h2>Laravel Ajax CRUD Example</h2>
		        </div>
		        <div class="pull-right">
				<button type="button" class="btn btn-success" data-toggle="modal" data-target="#create-item">
					  Create Item
				</button>
		        </div>
		    </div>
		</div>

		<table class="table table-bordered">
			<thead>
			    <tr>
				<th>Title</th>
				<th>Description</th>
				<th width="200px">Action</th>
			    </tr>
			</thead>
			<tbody>
			</tbody>
		</table>

		<ul id="pagination" class="pagination-sm"></ul>

	    <!-- Create Item Modal -->
		<div class="modal fade" id="create-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
		        <h4 class="modal-title" id="myModalLabel">Create Item</h4>
		      </div>
		      <div class="modal-body">

		      		<form data-toggle="validator" action="{{ route('item-ajax.store') }}" method="POST">
		      			<div class="form-group">
							<label class="control-label" for="title">Title:</label>
							<input type="text" name="title" class="form-control" data-error="Please enter title." required />
							<div class="help-block with-errors"></div>
						</div>
						<div class="form-group">
							<label class="control-label" for="title">Description:</label>
							<textarea name="description" class="form-control" data-error="Please enter description." required></textarea>
							<div class="help-block with-errors"></div>
						</div>
						<div class="form-group">
							<button type="submit" class="btn crud-submit btn-success">Submit</button>
						</div>
		      		</form>
		      </div>
		    </div>
		  </div>
		</div>

		<!-- Edit Item Modal -->
		<div class="modal fade" id="edit-item" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
		  <div class="modal-dialog" role="document">
		    <div class="modal-content">
		      <div class="modal-header">
		        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
		        <h4 class="modal-title" id="myModalLabel">Edit Item</h4>
		      </div>
		      <div class="modal-body">

		      		<form data-toggle="validator" action="/item-ajax/14" method="put">
		      			<div class="form-group">
							<label class="control-label" for="title">Title:</label>
							<input type="text" name="title" class="form-control" data-error="Please enter title." required />
							<div class="help-block with-errors"></div>
						</div>
						<div class="form-group">
							<label class="control-label" for="title">Description:</label>
							<textarea name="description" class="form-control" data-error="Please enter description." required></textarea>
							<div class="help-block with-errors"></div>
						</div>
						<div class="form-group">
							<button type="submit" class="btn btn-success crud-submit-edit">Submit</button>
						</div>
		      		</form>

		      </div>
		    </div>
		  </div>
		</div>

	</div>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.0/jquery.js"></script>
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha/js/bootstrap.min.js"></script>

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/twbs-pagination/1.3.1/jquery.twbsPagination.min.js"></script>

	<script src="https://cdnjs.cloudflare.com/ajax/libs/1000hz-bootstrap-validator/0.11.5/validator.min.js"></script>

	<script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
        <link href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet">

        <script type="text/javascript">
    	   var url = "<?php echo route('item-ajax.index')?>";
        </script>
        <script src="/js/item-ajax.js"></script> 

</body>
</html>

resources/views/presult.blade.php
<table class="table table-bordered">   
    <tr>
        <th>Name</th>
        <th>Details</th>          
    </tr>
    @foreach ($users as $user)
    <tr>
        <td>{{ $user->name }}</td>
        <td>{{ $user->email }}</td>
    </tr>
    @endforeach
 </table>
    {!! $users->render() !!}

resources/views/productlist.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
 <link rel="icon" type="image/x-icon" href="http://www.expertphp.in/images/favicon.ico" />
        <title> 
                Laravel AJAX Pagination with JQuery 
                </title>
    <meta name="description"  content="laravel ajax pagination with jquery demo,laravel pagination json demo,ajax pagination in laravel 5 demo,laravel 5 custom pagination demo.">
    <meta name="keywords" content="laravel ajax pagination with jquery demo,laravel pagination json demo,ajax pagination in laravel 5 demo,laravel 5 custom pagination demo.">

    <link href="http://demo.expertphp.in/css/style.css" rel="stylesheet">

     <link rel="stylesheet" href="http://www.expertphp.in/css/bootstrap.css" type="text/css" media="all" />
 <link href="http://demo.expertphp.in/css/jquery.ui.autocomplete.css" rel="stylesheet">
 
    <script src="http://demo.expertphp.in/js/jquery.js"></script>
    <script src="http://demo.expertphp.in/js/jquery-ui.min.js"></script>
  <script src='https://www.google.com/recaptcha/api.js'></script>

</head>
<body  style="background: #e1e1e1;">
 <div class="header">
    <a href="http://demo.expertphp.in">
        <img src="http://www.expertphp.in/images/logo.png" alt="logo">
        <strong>ExpertPHP.in <span class="demoh">Demo</span></strong>
    </a>
</div>

<div style="padding:20px;">
<br/>
<br/>

<div class="demo-head">
    <h1 class="post-title"> Demo - Laravel AJAX Pagination with JQuery  </h1>
    <a href="http://www.expertphp.in/article/laravel-5-ajax-pagination-with-jquery-example" class="btn btn-primary" style="border-radius:0px !important" target="_blank"> View Post</a>
</div>
<div style="text-align:center">
<script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
<!-- first ads -->
<ins class="adsbygoogle"
     style="display:inline-block;width:728px;height:90px"
     data-ad-client="ca-pub-5956923966420028"
     data-ad-slot="4990946392"
     data-ad-format="auto"></ins>
<script>
(adsbygoogle = window.adsbygoogle || []).push({});
</script>
</div>
<hr>


<div class="container">

    
   <div class="row"> 
<div class="col-md-8">
    
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Laravel AJAX Pagination with JQuery</h2>
            </div>
         
        </div>
    </div>
<div id="product_container">
       @include('presult')
</div>
<script>
 $(window).on('hashchange', function() {
        if (window.location.hash) {
            var page = window.location.hash.replace('#', '');
            if (page == Number.NaN || page <= 0) {
                return false;
            }else{
                getData(page);
            }
        }
    });
$(document).ready(function()
{
     $(document).on('click', '.pagination a',function(event)
    {
        $('li').removeClass('active');
        $(this).parent('li').addClass('active');
        event.preventDefault();
        var myurl = $(this).attr('href');
       var page=$(this).attr('href').split('page=')[1];
       getData(page);
    });
});
function getData(page){
        $.ajax(
        {
            url: '?page=' + page,
            type: "get",
            datatype: "html",
            // beforeSend: function()
            // {
            //     you can show your loader 
            // }
        })
        .done(function(data)
        {
            console.log(data);
            
            $("#product_container").empty().html(data);
            location.hash = page;
        })
        .fail(function(jqXHR, ajaxOptions, thrownError)
        {
              alert('No response from server');
        });
}
  </script>

  </div>

</div>
</div>
 


</div>

<hr/>
<script type="text/javascript"  src="http://www.expertphp.in/js/jquery/jquery.min.js "></script>
 <script type="text/javascript"  src="http://www.expertphp.in/js/bootstrap.js "></script>
</body>
</html>
  </body>
  </html>

resources/views/welcome2.blade.php
@extends('layouts.app')
<!--where we use top headers same as home page-->

@section('content')

    <div class="content">
                <div class="title m-b-md">
                    Welcome <br>
                    To <br>
                    INFINITE LOGIX SYSTEM
                </div>

                <div class="links">
                    <a href="https://laravel.com/docs">Documentation</a>
                    <a href="https://laracasts.com">Laracasts</a>
                    <a href="https://laravel-news.com">News</a>
                    <a href="https://forge.laravel.com">Forge</a>
                    <a href="https://github.com/laravel/laravel">GitHub</a>
                </div>
    </div>
    
@endsection